#!/bin/bash

./minimize --dp-path "$(pwd)"

#cd www/lib/global/php/miniki/
#~/Opensource/depage-cms/www/framework/i18n.sh
#cd -

rsync \
    --dry-run \
    -k -r -v -c \
    --exclude '.DS_Store' \
    --exclude '.git' \
    --exclude 'cache' \
    --exclude 'colors' \
    www/lib/ www-data@cms.depagecms.net:/var/www/net.depagecms.cms/projects/projectname/lib/
